DayReport/Controllers/YrhController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using DayReport.Models;
using Microsoft.AspNetCore.Authorization;

namespace DayReport.Controllers
{
   [Authorize]
    public class YrhController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Yrhho()
        {
            string datetime = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
            int hour = Convert.ToInt32(datetime.Substring(11, 2));
            Yrh yrh = new Yrh();
            DataSet ds = new DataSet();
            DataTable todayinhospital = yrh.Hotodayin();
            DataTable todayinhospitalo = yrh.HotodayinO();
            DataTable todayinhospitalv = yrh.HotodayinV();
            DataTable Gettodayinhospitalsum = yrh.Hotodaysum();
            ds.Tables.Add(todayinhospital);
            ds.Tables.Add(todayinhospitalo);
            ds.Tables.Add(todayinhospitalv);
            ds.Tables.Add(Gettodayinhospitalsum);
            return View(ds);
        }

        public IActionResult Yrhhi()
        {
            Yrh yrh = new Yrh();
            DataTable todayin = yrh.Hitodayin();
            DataTable todayout = yrh.Hitodayout();
            DataTable now = yrh.Hinow();
            DataTable peopleinursestation1 = yrh.Nursestation1();
            DataTable peopleinursestation2 = yrh.Nursestation2();
            DataTable peopleinursestation3 = yrh.Nursestation3();
            DataTable peopleinursestation4 = yrh.Nursestation4();
            DataTable peopleinursestation5 = yrh.Nursestation5();
            DataTable todayicu = yrh.Icunow();
            DataTable peopleinursestation6 = yrh.Nursestation6();


            DataSet ds = new DataSet();
            ds.Tables.Add(todayin);
            ds.Tables.Add(todayout);
            ds.Tables.Add(now);
            ds.Tables.Add(peopleinursestation1);
            ds.Tables.Add(peopleinursestation2);
            ds.Tables.Add(peopleinursestation3);
            ds.Tables.Add(peopleinursestation4);
            ds.Tables.Add(peopleinursestation5);
            ds.Tables.Add(todayicu);
            ds.Tables.Add(peopleinursestation6);
            return View(ds);
        }

        public IActionResult Yrhem()
        {
            Yrh yrh = new Yrh();
            DataSet ds = new DataSet();
            DataTable emtoday = yrh.Emtoday();
            DataTable emtodayfirst = yrh.Emtodayfirst();
            DataTable emtodaytransfer = yrh.Emtodaytransfer();
            DataTable emtotal = yrh.Emtodaysum();
            ds.Tables.Add(emtoday);
            ds.Tables.Add(emtodayfirst);
            ds.Tables.Add(emtodaytransfer);
            ds.Tables.Add(emtotal);
            return View(ds);
        }
    }
}

DayReport/Controllers/YshController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using DayReport.Models;
using Microsoft.AspNetCore.Authorization;

namespace DayReport.Controllers
{
   [Authorize]
    public class YshController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Yshho()
        {
            string datetime = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
            int hour = Convert.ToInt32(datetime.Substring(11, 2));
            Ysh ysh = new Ysh();
            DataSet ds = new DataSet();
            DataTable todayinhospital = ysh.Hotodayin();
            DataTable todayinhospitalo = ysh.HotodayinO();
            DataTable todayinhospitalv = ysh.HotodayinV();
            DataTable Gettodayinhospitalsum = ysh.Hotodaysum();
            ds.Tables.Add(todayinhospital);
            ds.Tables.Add(todayinhospitalo);
            ds.Tables.Add(todayinhospitalv);
            ds.Tables.Add(Gettodayinhospitalsum);
            return View(ds);
        }

        public IActionResult Yshhi()
        {
            Ysh ysh = new Ysh();
            DataTable todayin = ysh.Hitodayin();
            DataTable todayout = ysh.Hitodayout();
            DataTable now = ysh.Hinow();
            DataTable peopleinursestation1 = ysh.Nursestation1();
            DataTable peopleinursestation2 = ysh.Nursestation2();
            DataTable peopleinursestation3 = ysh.Nursestation3();
            DataTable peopleinursestation4 = ysh.Nursestation4();
            DataTable peopleinursestation5 = ysh.Nursestation5();
            DataTable todayicu = ysh.Icunow();
            DataTable peopleinursestation6 = ysh.Nursestation6();


            DataSet ds = new DataSet();
            ds.Tables.Add(todayin);
            ds.Tables.Add(todayout);
            ds.Tables.Add(now);
            ds.Tables.Add(peopleinursestation1);
            ds.Tables.Add(peopleinursestation2);
            ds.Tables.Add(peopleinursestation3);
            ds.Tables.Add(peopleinursestation4);
            ds.Tables.Add(peopleinursestation5);
            ds.Tables.Add(todayicu);
            ds.Tables.Add(peopleinursestation6);
            return View(ds);
        }

        public IActionResult Yshem()
        {
            Ysh ysh = new Ysh();
            DataSet ds = new DataSet();
            DataTable emtoday = ysh.Emtoday();
            DataTable emtodayfirst = ysh.Emtodayfirst();
            DataTable emtodaytransfer = ysh.Emtodaytransfer();
            DataTable emtotal = ysh.Emtodaysum();
            ds.Tables.Add(emtoday);
            ds.Tables.Add(emtodayfirst);
            ds.Tables.Add(emtodaytransfer);
            ds.Tables.Add(emtotal);
            return View(ds);
        }
    }
}

DayReport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lux.css"  />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/table2excel.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">門急住即時報表</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yrh" asp-action="Yrhho">員榮門診</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yrh" asp-action="Yrhem">員榮急診</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yrh" asp-action="Yrhhi">員榮住院</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ysh" asp-action="Yshho">員生門診</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ysh" asp-action="Yshem">員生急診</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ysh" asp-action="Yshhi">員生住院</a>
                        </li>
                    </ul>
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("登出", "Logout", "Account", new { area = "" }, null)</li>
                            </ul>
                        }
                        else
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("登入", "Login", "Account", new { area = "" }, null)</li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021~2023 員榮醫院
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>